sudo: false
dist: trusty
language: node_js
node_js: 6

before_install:
  - npm install
  - export PATH=$PATH:$(pwd)/node_modules/.bin

script:
  - testrpc > /dev/null &
  - truffle test

cache:
  directories:
    - node_modules

notifications:
  slack: chrono-dev:a6jsr4kW5U4uxrGNOxygOWGF
